/*
 * Actualiza Datos Generales API Simulacion
 * <p>API de Actualiza Datos Generales.</p><br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.ActualizaDatosGeneralesSimulacion.client.api;

import io.ActualizaDatosGeneralesSimulacion.client.ApiClient;
import io.ActualizaDatosGeneralesSimulacion.client.ApiResponse;
import io.ActualizaDatosGeneralesSimulacion.client.model.CatalogoEstados;
import io.ActualizaDatosGeneralesSimulacion.client.model.Errores;
import io.ActualizaDatosGeneralesSimulacion.client.model.RequestADG;
import io.ActualizaDatosGeneralesSimulacion.client.model.RespuestaADG;
import org.junit.Test;
import org.junit.Ignore;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import java.util.concurrent.TimeUnit;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import okhttp3.OkHttpClient;

/**
 * API tests for AdgPorCuentaApi
 */
public class AdgPorCuentaApiTest {

    private Logger logger = LoggerFactory.getLogger(AdgPorCuentaApiTest.class.getName());
    private final AdgPorCuentaApi api = new AdgPorCuentaApi();
    private ApiClient apiClient = null;   

    @Before()
    public void setUp() {
        this.apiClient = api.getApiClient();
        this.apiClient.setBasePath("https://services.circulodecredito.com.mx/sandbox/v1/adg");
        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .readTimeout(30, TimeUnit.SECONDS)
                .build();
        apiClient.setHttpClient(okHttpClient);
    }    
    
    /**
     * Actualiza Datos Generales por cuenta
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void porCuentaPostTest() throws Exception {
        Integer estatusOK = 200;
        String xApiKey = "x-api-key";
        RequestADG requestBody = new RequestADG();
        requestBody.setClaveEstado(CatalogoEstados.GRO);
        requestBody.setNumOtorgante("111111");
        requestBody.setCuenta("TO");
        requestBody.setCp("86621");
        requestBody.setFolioOtorgante("33333");
        ApiResponse<RespuestaADG> response = api.porCuentaPostWithHttpInfo(xApiKey, requestBody);

        // TODO: test validations

        Assert.assertTrue(estatusOK.equals(response.getStatusCode()));
            
        if(estatusOK.equals(response.getStatusCode())) {
            RespuestaADG responseOK = (RespuestaADG) response.getData();
            logger.info(responseOK.toString());
        }

    }
    
}
