/*
 * Actualiza Datos Generales API Simulacion
 * <p>API de Actualiza Datos Generales.</p><br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.ActualizaDatosGeneralesSimulacion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RespuestaADGPersonaADG
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-04T22:09:16.181Z")
public class RespuestaADGPersonaADG {
  @SerializedName("numeroCuenta")
  private String numeroCuenta = null;

  @SerializedName("apellidoPaterno")
  private String apellidoPaterno = null;

  @SerializedName("apellidoMaterno")
  private String apellidoMaterno = null;

  @SerializedName("nombres")
  private String nombres = null;

  @SerializedName("fechaNac")
  private String fechaNac = null;

  @SerializedName("rfc")
  private String rfc = null;

  @SerializedName("curp")
  private String curp = null;

  @SerializedName("sexo")
  private String sexo = null;

  public RespuestaADGPersonaADG numeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
    return this;
  }

   /**
   * Get numeroCuenta
   * @return numeroCuenta
  **/
  @ApiModelProperty(example = "IC270220186999", value = "")
  public String getNumeroCuenta() {
    return numeroCuenta;
  }

  public void setNumeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
  }

  public RespuestaADGPersonaADG apellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
    return this;
  }

   /**
   * Get apellidoPaterno
   * @return apellidoPaterno
  **/
  @ApiModelProperty(example = "DKDK", value = "")
  public String getApellidoPaterno() {
    return apellidoPaterno;
  }

  public void setApellidoPaterno(String apellidoPaterno) {
    this.apellidoPaterno = apellidoPaterno;
  }

  public RespuestaADGPersonaADG apellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
    return this;
  }

   /**
   * Get apellidoMaterno
   * @return apellidoMaterno
  **/
  @ApiModelProperty(example = "GKFK", value = "")
  public String getApellidoMaterno() {
    return apellidoMaterno;
  }

  public void setApellidoMaterno(String apellidoMaterno) {
    this.apellidoMaterno = apellidoMaterno;
  }

  public RespuestaADGPersonaADG nombres(String nombres) {
    this.nombres = nombres;
    return this;
  }

   /**
   * Get nombres
   * @return nombres
  **/
  @ApiModelProperty(example = "NUEVO", value = "")
  public String getNombres() {
    return nombres;
  }

  public void setNombres(String nombres) {
    this.nombres = nombres;
  }

  public RespuestaADGPersonaADG fechaNac(String fechaNac) {
    this.fechaNac = fechaNac;
    return this;
  }

   /**
   * Get fechaNac
   * @return fechaNac
  **/
  @ApiModelProperty(example = "11/09/1991", value = "")
  public String getFechaNac() {
    return fechaNac;
  }

  public void setFechaNac(String fechaNac) {
    this.fechaNac = fechaNac;
  }

  public RespuestaADGPersonaADG rfc(String rfc) {
    this.rfc = rfc;
    return this;
  }

   /**
   * Get rfc
   * @return rfc
  **/
  @ApiModelProperty(example = "DXGN910911", value = "")
  public String getRfc() {
    return rfc;
  }

  public void setRfc(String rfc) {
    this.rfc = rfc;
  }

  public RespuestaADGPersonaADG curp(String curp) {
    this.curp = curp;
    return this;
  }

   /**
   * Get curp
   * @return curp
  **/
  @ApiModelProperty(example = "", value = "")
  public String getCurp() {
    return curp;
  }

  public void setCurp(String curp) {
    this.curp = curp;
  }

  public RespuestaADGPersonaADG sexo(String sexo) {
    this.sexo = sexo;
    return this;
  }

   /**
   * Get sexo
   * @return sexo
  **/
  @ApiModelProperty(example = "", value = "")
  public String getSexo() {
    return sexo;
  }

  public void setSexo(String sexo) {
    this.sexo = sexo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaADGPersonaADG respuestaADGPersonaADG = (RespuestaADGPersonaADG) o;
    return Objects.equals(this.numeroCuenta, respuestaADGPersonaADG.numeroCuenta) &&
        Objects.equals(this.apellidoPaterno, respuestaADGPersonaADG.apellidoPaterno) &&
        Objects.equals(this.apellidoMaterno, respuestaADGPersonaADG.apellidoMaterno) &&
        Objects.equals(this.nombres, respuestaADGPersonaADG.nombres) &&
        Objects.equals(this.fechaNac, respuestaADGPersonaADG.fechaNac) &&
        Objects.equals(this.rfc, respuestaADGPersonaADG.rfc) &&
        Objects.equals(this.curp, respuestaADGPersonaADG.curp) &&
        Objects.equals(this.sexo, respuestaADGPersonaADG.sexo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCuenta, apellidoPaterno, apellidoMaterno, nombres, fechaNac, rfc, curp, sexo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaADGPersonaADG {\n");
    
    sb.append("    numeroCuenta: ").append(toIndentedString(numeroCuenta)).append("\n");
    sb.append("    apellidoPaterno: ").append(toIndentedString(apellidoPaterno)).append("\n");
    sb.append("    apellidoMaterno: ").append(toIndentedString(apellidoMaterno)).append("\n");
    sb.append("    nombres: ").append(toIndentedString(nombres)).append("\n");
    sb.append("    fechaNac: ").append(toIndentedString(fechaNac)).append("\n");
    sb.append("    rfc: ").append(toIndentedString(rfc)).append("\n");
    sb.append("    curp: ").append(toIndentedString(curp)).append("\n");
    sb.append("    sexo: ").append(toIndentedString(sexo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

