/*
 * Actualiza Datos Generales API Simulacion
 * <p>API de Actualiza Datos Generales.</p><br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.ActualizaDatosGeneralesSimulacion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RespuestaADGEmpleoADG
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-04T22:09:16.181Z")
public class RespuestaADGEmpleoADG {
  @SerializedName("numeroCuenta")
  private String numeroCuenta = null;

  @SerializedName("empleo")
  private String empleo = null;

  @SerializedName("calleEmpleo")
  private String calleEmpleo = null;

  @SerializedName("coloniaEmpleo")
  private String coloniaEmpleo = null;

  @SerializedName("ciudadEmpleo")
  private String ciudadEmpleo = null;

  @SerializedName("telefonoEmpleo")
  private String telefonoEmpleo = null;

  @SerializedName("puesto")
  private String puesto = null;

  @SerializedName("salario")
  private String salario = null;

  @SerializedName("estadoEmpleo")
  private String estadoEmpleo = null;

  @SerializedName("municipioEmpleo")
  private String municipioEmpleo = null;

  @SerializedName("cpEmpleo")
  private String cpEmpleo = null;

  @SerializedName("fechaAlta")
  private String fechaAlta = null;

  public RespuestaADGEmpleoADG numeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
    return this;
  }

   /**
   * Get numeroCuenta
   * @return numeroCuenta
  **/
  @ApiModelProperty(example = "IC270220186999", value = "")
  public String getNumeroCuenta() {
    return numeroCuenta;
  }

  public void setNumeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
  }

  public RespuestaADGEmpleoADG empleo(String empleo) {
    this.empleo = empleo;
    return this;
  }

   /**
   * Get empleo
   * @return empleo
  **/
  @ApiModelProperty(example = "FARMACIA GENERICOS 123", value = "")
  public String getEmpleo() {
    return empleo;
  }

  public void setEmpleo(String empleo) {
    this.empleo = empleo;
  }

  public RespuestaADGEmpleoADG calleEmpleo(String calleEmpleo) {
    this.calleEmpleo = calleEmpleo;
    return this;
  }

   /**
   * Get calleEmpleo
   * @return calleEmpleo
  **/
  @ApiModelProperty(example = "AV 3 CALLE 15", value = "")
  public String getCalleEmpleo() {
    return calleEmpleo;
  }

  public void setCalleEmpleo(String calleEmpleo) {
    this.calleEmpleo = calleEmpleo;
  }

  public RespuestaADGEmpleoADG coloniaEmpleo(String coloniaEmpleo) {
    this.coloniaEmpleo = coloniaEmpleo;
    return this;
  }

   /**
   * Get coloniaEmpleo
   * @return coloniaEmpleo
  **/
  @ApiModelProperty(example = "", value = "")
  public String getColoniaEmpleo() {
    return coloniaEmpleo;
  }

  public void setColoniaEmpleo(String coloniaEmpleo) {
    this.coloniaEmpleo = coloniaEmpleo;
  }

  public RespuestaADGEmpleoADG ciudadEmpleo(String ciudadEmpleo) {
    this.ciudadEmpleo = ciudadEmpleo;
    return this;
  }

   /**
   * Get ciudadEmpleo
   * @return ciudadEmpleo
  **/
  @ApiModelProperty(example = "", value = "")
  public String getCiudadEmpleo() {
    return ciudadEmpleo;
  }

  public void setCiudadEmpleo(String ciudadEmpleo) {
    this.ciudadEmpleo = ciudadEmpleo;
  }

  public RespuestaADGEmpleoADG telefonoEmpleo(String telefonoEmpleo) {
    this.telefonoEmpleo = telefonoEmpleo;
    return this;
  }

   /**
   * Get telefonoEmpleo
   * @return telefonoEmpleo
  **/
  @ApiModelProperty(example = "2717128020", value = "")
  public String getTelefonoEmpleo() {
    return telefonoEmpleo;
  }

  public void setTelefonoEmpleo(String telefonoEmpleo) {
    this.telefonoEmpleo = telefonoEmpleo;
  }

  public RespuestaADGEmpleoADG puesto(String puesto) {
    this.puesto = puesto;
    return this;
  }

   /**
   * Get puesto
   * @return puesto
  **/
  @ApiModelProperty(example = "ENTRETENIMIENTO", value = "")
  public String getPuesto() {
    return puesto;
  }

  public void setPuesto(String puesto) {
    this.puesto = puesto;
  }

  public RespuestaADGEmpleoADG salario(String salario) {
    this.salario = salario;
    return this;
  }

   /**
   * Get salario
   * @return salario
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getSalario() {
    return salario;
  }

  public void setSalario(String salario) {
    this.salario = salario;
  }

  public RespuestaADGEmpleoADG estadoEmpleo(String estadoEmpleo) {
    this.estadoEmpleo = estadoEmpleo;
    return this;
  }

   /**
   * Get estadoEmpleo
   * @return estadoEmpleo
  **/
  @ApiModelProperty(example = "", value = "")
  public String getEstadoEmpleo() {
    return estadoEmpleo;
  }

  public void setEstadoEmpleo(String estadoEmpleo) {
    this.estadoEmpleo = estadoEmpleo;
  }

  public RespuestaADGEmpleoADG municipioEmpleo(String municipioEmpleo) {
    this.municipioEmpleo = municipioEmpleo;
    return this;
  }

   /**
   * Get municipioEmpleo
   * @return municipioEmpleo
  **/
  @ApiModelProperty(example = "CORDOBA", value = "")
  public String getMunicipioEmpleo() {
    return municipioEmpleo;
  }

  public void setMunicipioEmpleo(String municipioEmpleo) {
    this.municipioEmpleo = municipioEmpleo;
  }

  public RespuestaADGEmpleoADG cpEmpleo(String cpEmpleo) {
    this.cpEmpleo = cpEmpleo;
    return this;
  }

   /**
   * Get cpEmpleo
   * @return cpEmpleo
  **/
  @ApiModelProperty(example = "00000", value = "")
  public String getCpEmpleo() {
    return cpEmpleo;
  }

  public void setCpEmpleo(String cpEmpleo) {
    this.cpEmpleo = cpEmpleo;
  }

  public RespuestaADGEmpleoADG fechaAlta(String fechaAlta) {
    this.fechaAlta = fechaAlta;
    return this;
  }

   /**
   * Get fechaAlta
   * @return fechaAlta
  **/
  @ApiModelProperty(example = "12/05/2012", value = "")
  public String getFechaAlta() {
    return fechaAlta;
  }

  public void setFechaAlta(String fechaAlta) {
    this.fechaAlta = fechaAlta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaADGEmpleoADG respuestaADGEmpleoADG = (RespuestaADGEmpleoADG) o;
    return Objects.equals(this.numeroCuenta, respuestaADGEmpleoADG.numeroCuenta) &&
        Objects.equals(this.empleo, respuestaADGEmpleoADG.empleo) &&
        Objects.equals(this.calleEmpleo, respuestaADGEmpleoADG.calleEmpleo) &&
        Objects.equals(this.coloniaEmpleo, respuestaADGEmpleoADG.coloniaEmpleo) &&
        Objects.equals(this.ciudadEmpleo, respuestaADGEmpleoADG.ciudadEmpleo) &&
        Objects.equals(this.telefonoEmpleo, respuestaADGEmpleoADG.telefonoEmpleo) &&
        Objects.equals(this.puesto, respuestaADGEmpleoADG.puesto) &&
        Objects.equals(this.salario, respuestaADGEmpleoADG.salario) &&
        Objects.equals(this.estadoEmpleo, respuestaADGEmpleoADG.estadoEmpleo) &&
        Objects.equals(this.municipioEmpleo, respuestaADGEmpleoADG.municipioEmpleo) &&
        Objects.equals(this.cpEmpleo, respuestaADGEmpleoADG.cpEmpleo) &&
        Objects.equals(this.fechaAlta, respuestaADGEmpleoADG.fechaAlta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCuenta, empleo, calleEmpleo, coloniaEmpleo, ciudadEmpleo, telefonoEmpleo, puesto, salario, estadoEmpleo, municipioEmpleo, cpEmpleo, fechaAlta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaADGEmpleoADG {\n");
    
    sb.append("    numeroCuenta: ").append(toIndentedString(numeroCuenta)).append("\n");
    sb.append("    empleo: ").append(toIndentedString(empleo)).append("\n");
    sb.append("    calleEmpleo: ").append(toIndentedString(calleEmpleo)).append("\n");
    sb.append("    coloniaEmpleo: ").append(toIndentedString(coloniaEmpleo)).append("\n");
    sb.append("    ciudadEmpleo: ").append(toIndentedString(ciudadEmpleo)).append("\n");
    sb.append("    telefonoEmpleo: ").append(toIndentedString(telefonoEmpleo)).append("\n");
    sb.append("    puesto: ").append(toIndentedString(puesto)).append("\n");
    sb.append("    salario: ").append(toIndentedString(salario)).append("\n");
    sb.append("    estadoEmpleo: ").append(toIndentedString(estadoEmpleo)).append("\n");
    sb.append("    municipioEmpleo: ").append(toIndentedString(municipioEmpleo)).append("\n");
    sb.append("    cpEmpleo: ").append(toIndentedString(cpEmpleo)).append("\n");
    sb.append("    fechaAlta: ").append(toIndentedString(fechaAlta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

