/*
 * Actualiza Datos Generales API Simulacion
 * <p>API de Actualiza Datos Generales.</p><br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.ActualizaDatosGeneralesSimulacion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RespuestaADGDomicilioADG
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-04T22:09:16.181Z")
public class RespuestaADGDomicilioADG {
  @SerializedName("numeroCuenta")
  private String numeroCuenta = null;

  @SerializedName("calle")
  private String calle = null;

  @SerializedName("colonia")
  private String colonia = null;

  @SerializedName("ciudad")
  private String ciudad = null;

  @SerializedName("telefono")
  private String telefono = null;

  @SerializedName("estado")
  private String estado = null;

  @SerializedName("municipio")
  private String municipio = null;

  @SerializedName("cp")
  private String cp = null;

  @SerializedName("fechaAlta")
  private String fechaAlta = null;

  @SerializedName("tipoAlta")
  private String tipoAlta = null;

  @SerializedName("numConsultas")
  private String numConsultas = null;

  @SerializedName("fechaUltimaConsulta")
  private String fechaUltimaConsulta = null;

  @SerializedName("comparacionCP")
  private String comparacionCP = null;

  @SerializedName("comparacionEstado")
  private String comparacionEstado = null;

  @SerializedName("comparacionTel")
  private String comparacionTel = null;

  @SerializedName("FolioDomicilio")
  private String folioDomicilio = null;

  public RespuestaADGDomicilioADG numeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
    return this;
  }

   /**
   * Get numeroCuenta
   * @return numeroCuenta
  **/
  @ApiModelProperty(example = "IC270220186999", value = "")
  public String getNumeroCuenta() {
    return numeroCuenta;
  }

  public void setNumeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
  }

  public RespuestaADGDomicilioADG calle(String calle) {
    this.calle = calle;
    return this;
  }

   /**
   * Get calle
   * @return calle
  **/
  @ApiModelProperty(example = "MEXICO 149", value = "")
  public String getCalle() {
    return calle;
  }

  public void setCalle(String calle) {
    this.calle = calle;
  }

  public RespuestaADGDomicilioADG colonia(String colonia) {
    this.colonia = colonia;
    return this;
  }

   /**
   * Get colonia
   * @return colonia
  **/
  @ApiModelProperty(example = "ESTACION COYOTES JOSE MARIA MORELOS", value = "")
  public String getColonia() {
    return colonia;
  }

  public void setColonia(String colonia) {
    this.colonia = colonia;
  }

  public RespuestaADGDomicilioADG ciudad(String ciudad) {
    this.ciudad = ciudad;
    return this;
  }

   /**
   * Get ciudad
   * @return ciudad
  **/
  @ApiModelProperty(example = "", value = "")
  public String getCiudad() {
    return ciudad;
  }

  public void setCiudad(String ciudad) {
    this.ciudad = ciudad;
  }

  public RespuestaADGDomicilioADG telefono(String telefono) {
    this.telefono = telefono;
    return this;
  }

   /**
   * Get telefono
   * @return telefono
  **/
  @ApiModelProperty(example = "", value = "")
  public String getTelefono() {
    return telefono;
  }

  public void setTelefono(String telefono) {
    this.telefono = telefono;
  }

  public RespuestaADGDomicilioADG estado(String estado) {
    this.estado = estado;
    return this;
  }

   /**
   * Get estado
   * @return estado
  **/
  @ApiModelProperty(example = "DGO", value = "")
  public String getEstado() {
    return estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public RespuestaADGDomicilioADG municipio(String municipio) {
    this.municipio = municipio;
    return this;
  }

   /**
   * Get municipio
   * @return municipio
  **/
  @ApiModelProperty(example = "PUEBLO NUEVO", value = "")
  public String getMunicipio() {
    return municipio;
  }

  public void setMunicipio(String municipio) {
    this.municipio = municipio;
  }

  public RespuestaADGDomicilioADG cp(String cp) {
    this.cp = cp;
    return this;
  }

   /**
   * Get cp
   * @return cp
  **/
  @ApiModelProperty(example = "34950", value = "")
  public String getCp() {
    return cp;
  }

  public void setCp(String cp) {
    this.cp = cp;
  }

  public RespuestaADGDomicilioADG fechaAlta(String fechaAlta) {
    this.fechaAlta = fechaAlta;
    return this;
  }

   /**
   * Get fechaAlta
   * @return fechaAlta
  **/
  @ApiModelProperty(example = "20/02/2023", value = "")
  public String getFechaAlta() {
    return fechaAlta;
  }

  public void setFechaAlta(String fechaAlta) {
    this.fechaAlta = fechaAlta;
  }

  public RespuestaADGDomicilioADG tipoAlta(String tipoAlta) {
    this.tipoAlta = tipoAlta;
    return this;
  }

   /**
   * Get tipoAlta
   * @return tipoAlta
  **/
  @ApiModelProperty(example = "CONSULTA", value = "")
  public String getTipoAlta() {
    return tipoAlta;
  }

  public void setTipoAlta(String tipoAlta) {
    this.tipoAlta = tipoAlta;
  }

  public RespuestaADGDomicilioADG numConsultas(String numConsultas) {
    this.numConsultas = numConsultas;
    return this;
  }

   /**
   * Get numConsultas
   * @return numConsultas
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getNumConsultas() {
    return numConsultas;
  }

  public void setNumConsultas(String numConsultas) {
    this.numConsultas = numConsultas;
  }

  public RespuestaADGDomicilioADG fechaUltimaConsulta(String fechaUltimaConsulta) {
    this.fechaUltimaConsulta = fechaUltimaConsulta;
    return this;
  }

   /**
   * Get fechaUltimaConsulta
   * @return fechaUltimaConsulta
  **/
  @ApiModelProperty(example = "20/02/2023", value = "")
  public String getFechaUltimaConsulta() {
    return fechaUltimaConsulta;
  }

  public void setFechaUltimaConsulta(String fechaUltimaConsulta) {
    this.fechaUltimaConsulta = fechaUltimaConsulta;
  }

  public RespuestaADGDomicilioADG comparacionCP(String comparacionCP) {
    this.comparacionCP = comparacionCP;
    return this;
  }

   /**
   * Get comparacionCP
   * @return comparacionCP
  **/
  @ApiModelProperty(example = "MISMO CP", value = "")
  public String getComparacionCP() {
    return comparacionCP;
  }

  public void setComparacionCP(String comparacionCP) {
    this.comparacionCP = comparacionCP;
  }

  public RespuestaADGDomicilioADG comparacionEstado(String comparacionEstado) {
    this.comparacionEstado = comparacionEstado;
    return this;
  }

   /**
   * Get comparacionEstado
   * @return comparacionEstado
  **/
  @ApiModelProperty(example = "MISMO ESTADO", value = "")
  public String getComparacionEstado() {
    return comparacionEstado;
  }

  public void setComparacionEstado(String comparacionEstado) {
    this.comparacionEstado = comparacionEstado;
  }

  public RespuestaADGDomicilioADG comparacionTel(String comparacionTel) {
    this.comparacionTel = comparacionTel;
    return this;
  }

   /**
   * Get comparacionTel
   * @return comparacionTel
  **/
  @ApiModelProperty(example = "", value = "")
  public String getComparacionTel() {
    return comparacionTel;
  }

  public void setComparacionTel(String comparacionTel) {
    this.comparacionTel = comparacionTel;
  }

  public RespuestaADGDomicilioADG folioDomicilio(String folioDomicilio) {
    this.folioDomicilio = folioDomicilio;
    return this;
  }

   /**
   * Get folioDomicilio
   * @return folioDomicilio
  **/
  @ApiModelProperty(example = "229626913", value = "")
  public String getFolioDomicilio() {
    return folioDomicilio;
  }

  public void setFolioDomicilio(String folioDomicilio) {
    this.folioDomicilio = folioDomicilio;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaADGDomicilioADG respuestaADGDomicilioADG = (RespuestaADGDomicilioADG) o;
    return Objects.equals(this.numeroCuenta, respuestaADGDomicilioADG.numeroCuenta) &&
        Objects.equals(this.calle, respuestaADGDomicilioADG.calle) &&
        Objects.equals(this.colonia, respuestaADGDomicilioADG.colonia) &&
        Objects.equals(this.ciudad, respuestaADGDomicilioADG.ciudad) &&
        Objects.equals(this.telefono, respuestaADGDomicilioADG.telefono) &&
        Objects.equals(this.estado, respuestaADGDomicilioADG.estado) &&
        Objects.equals(this.municipio, respuestaADGDomicilioADG.municipio) &&
        Objects.equals(this.cp, respuestaADGDomicilioADG.cp) &&
        Objects.equals(this.fechaAlta, respuestaADGDomicilioADG.fechaAlta) &&
        Objects.equals(this.tipoAlta, respuestaADGDomicilioADG.tipoAlta) &&
        Objects.equals(this.numConsultas, respuestaADGDomicilioADG.numConsultas) &&
        Objects.equals(this.fechaUltimaConsulta, respuestaADGDomicilioADG.fechaUltimaConsulta) &&
        Objects.equals(this.comparacionCP, respuestaADGDomicilioADG.comparacionCP) &&
        Objects.equals(this.comparacionEstado, respuestaADGDomicilioADG.comparacionEstado) &&
        Objects.equals(this.comparacionTel, respuestaADGDomicilioADG.comparacionTel) &&
        Objects.equals(this.folioDomicilio, respuestaADGDomicilioADG.folioDomicilio);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCuenta, calle, colonia, ciudad, telefono, estado, municipio, cp, fechaAlta, tipoAlta, numConsultas, fechaUltimaConsulta, comparacionCP, comparacionEstado, comparacionTel, folioDomicilio);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaADGDomicilioADG {\n");
    
    sb.append("    numeroCuenta: ").append(toIndentedString(numeroCuenta)).append("\n");
    sb.append("    calle: ").append(toIndentedString(calle)).append("\n");
    sb.append("    colonia: ").append(toIndentedString(colonia)).append("\n");
    sb.append("    ciudad: ").append(toIndentedString(ciudad)).append("\n");
    sb.append("    telefono: ").append(toIndentedString(telefono)).append("\n");
    sb.append("    estado: ").append(toIndentedString(estado)).append("\n");
    sb.append("    municipio: ").append(toIndentedString(municipio)).append("\n");
    sb.append("    cp: ").append(toIndentedString(cp)).append("\n");
    sb.append("    fechaAlta: ").append(toIndentedString(fechaAlta)).append("\n");
    sb.append("    tipoAlta: ").append(toIndentedString(tipoAlta)).append("\n");
    sb.append("    numConsultas: ").append(toIndentedString(numConsultas)).append("\n");
    sb.append("    fechaUltimaConsulta: ").append(toIndentedString(fechaUltimaConsulta)).append("\n");
    sb.append("    comparacionCP: ").append(toIndentedString(comparacionCP)).append("\n");
    sb.append("    comparacionEstado: ").append(toIndentedString(comparacionEstado)).append("\n");
    sb.append("    comparacionTel: ").append(toIndentedString(comparacionTel)).append("\n");
    sb.append("    folioDomicilio: ").append(toIndentedString(folioDomicilio)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

