/*
 * Actualiza Datos Generales API Simulacion
 * <p>API de Actualiza Datos Generales.</p><br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2020-10/circulo_de_credito-apihub.png' height='40' width='220'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.ActualizaDatosGeneralesSimulacion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RespuestaADGVariablesDomicilio
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-04-04T22:09:16.181Z")
public class RespuestaADGVariablesDomicilio {
  @SerializedName("numeroCuenta")
  private String numeroCuenta = null;

  @SerializedName("folioDomicilio")
  private String folioDomicilio = null;

  @SerializedName("fechaUltimaConsulta")
  private String fechaUltimaConsulta = null;

  @SerializedName("numCreditos")
  private String numCreditos = null;

  @SerializedName("numCreditosTresMeses")
  private String numCreditosTresMeses = null;

  @SerializedName("numCreditosTresMesesNos")
  private String numCreditosTresMesesNos = null;

  @SerializedName("otorgantesConsulta")
  private String otorgantesConsulta = null;

  @SerializedName("otorgantesConsultaTresMeses")
  private String otorgantesConsultaTresMeses = null;

  @SerializedName("otorgantesCarga")
  private String otorgantesCarga = null;

  @SerializedName("otorgantesCargaTresMeses")
  private String otorgantesCargaTresMeses = null;

  @SerializedName("otorgantesCargaTresMesesNos")
  private String otorgantesCargaTresMesesNos = null;

  @SerializedName("servicioCarga")
  private String servicioCarga = null;

  @SerializedName("servicioCargaTresMeses")
  private String servicioCargaTresMeses = null;

  @SerializedName("servicioConsulta")
  private String servicioConsulta = null;

  @SerializedName("servicioConsultaTresMeses")
  private String servicioConsultaTresMeses = null;

  @SerializedName("numMiembros")
  private String numMiembros = null;

  @SerializedName("miembrosCredito")
  private String miembrosCredito = null;

  @SerializedName("miembrosCreditoS")
  private String miembrosCreditoS = null;

  @SerializedName("miembrosCreditoNos")
  private String miembrosCreditoNos = null;

  @SerializedName("miembrosConsulta")
  private String miembrosConsulta = null;

  @SerializedName("miembrosConsultaTresMeses")
  private String miembrosConsultaTresMeses = null;

  @SerializedName("calif")
  private String calif = null;

  public RespuestaADGVariablesDomicilio numeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
    return this;
  }

   /**
   * Get numeroCuenta
   * @return numeroCuenta
  **/
  @ApiModelProperty(example = "IC270220186999", value = "")
  public String getNumeroCuenta() {
    return numeroCuenta;
  }

  public void setNumeroCuenta(String numeroCuenta) {
    this.numeroCuenta = numeroCuenta;
  }

  public RespuestaADGVariablesDomicilio folioDomicilio(String folioDomicilio) {
    this.folioDomicilio = folioDomicilio;
    return this;
  }

   /**
   * Get folioDomicilio
   * @return folioDomicilio
  **/
  @ApiModelProperty(example = "229626913", value = "")
  public String getFolioDomicilio() {
    return folioDomicilio;
  }

  public void setFolioDomicilio(String folioDomicilio) {
    this.folioDomicilio = folioDomicilio;
  }

  public RespuestaADGVariablesDomicilio fechaUltimaConsulta(String fechaUltimaConsulta) {
    this.fechaUltimaConsulta = fechaUltimaConsulta;
    return this;
  }

   /**
   * Get fechaUltimaConsulta
   * @return fechaUltimaConsulta
  **/
  @ApiModelProperty(example = "2018-05-09 16:28:28", value = "")
  public String getFechaUltimaConsulta() {
    return fechaUltimaConsulta;
  }

  public void setFechaUltimaConsulta(String fechaUltimaConsulta) {
    this.fechaUltimaConsulta = fechaUltimaConsulta;
  }

  public RespuestaADGVariablesDomicilio numCreditos(String numCreditos) {
    this.numCreditos = numCreditos;
    return this;
  }

   /**
   * Get numCreditos
   * @return numCreditos
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getNumCreditos() {
    return numCreditos;
  }

  public void setNumCreditos(String numCreditos) {
    this.numCreditos = numCreditos;
  }

  public RespuestaADGVariablesDomicilio numCreditosTresMeses(String numCreditosTresMeses) {
    this.numCreditosTresMeses = numCreditosTresMeses;
    return this;
  }

   /**
   * Get numCreditosTresMeses
   * @return numCreditosTresMeses
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getNumCreditosTresMeses() {
    return numCreditosTresMeses;
  }

  public void setNumCreditosTresMeses(String numCreditosTresMeses) {
    this.numCreditosTresMeses = numCreditosTresMeses;
  }

  public RespuestaADGVariablesDomicilio numCreditosTresMesesNos(String numCreditosTresMesesNos) {
    this.numCreditosTresMesesNos = numCreditosTresMesesNos;
    return this;
  }

   /**
   * Get numCreditosTresMesesNos
   * @return numCreditosTresMesesNos
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getNumCreditosTresMesesNos() {
    return numCreditosTresMesesNos;
  }

  public void setNumCreditosTresMesesNos(String numCreditosTresMesesNos) {
    this.numCreditosTresMesesNos = numCreditosTresMesesNos;
  }

  public RespuestaADGVariablesDomicilio otorgantesConsulta(String otorgantesConsulta) {
    this.otorgantesConsulta = otorgantesConsulta;
    return this;
  }

   /**
   * Get otorgantesConsulta
   * @return otorgantesConsulta
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getOtorgantesConsulta() {
    return otorgantesConsulta;
  }

  public void setOtorgantesConsulta(String otorgantesConsulta) {
    this.otorgantesConsulta = otorgantesConsulta;
  }

  public RespuestaADGVariablesDomicilio otorgantesConsultaTresMeses(String otorgantesConsultaTresMeses) {
    this.otorgantesConsultaTresMeses = otorgantesConsultaTresMeses;
    return this;
  }

   /**
   * Get otorgantesConsultaTresMeses
   * @return otorgantesConsultaTresMeses
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getOtorgantesConsultaTresMeses() {
    return otorgantesConsultaTresMeses;
  }

  public void setOtorgantesConsultaTresMeses(String otorgantesConsultaTresMeses) {
    this.otorgantesConsultaTresMeses = otorgantesConsultaTresMeses;
  }

  public RespuestaADGVariablesDomicilio otorgantesCarga(String otorgantesCarga) {
    this.otorgantesCarga = otorgantesCarga;
    return this;
  }

   /**
   * Get otorgantesCarga
   * @return otorgantesCarga
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getOtorgantesCarga() {
    return otorgantesCarga;
  }

  public void setOtorgantesCarga(String otorgantesCarga) {
    this.otorgantesCarga = otorgantesCarga;
  }

  public RespuestaADGVariablesDomicilio otorgantesCargaTresMeses(String otorgantesCargaTresMeses) {
    this.otorgantesCargaTresMeses = otorgantesCargaTresMeses;
    return this;
  }

   /**
   * Get otorgantesCargaTresMeses
   * @return otorgantesCargaTresMeses
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getOtorgantesCargaTresMeses() {
    return otorgantesCargaTresMeses;
  }

  public void setOtorgantesCargaTresMeses(String otorgantesCargaTresMeses) {
    this.otorgantesCargaTresMeses = otorgantesCargaTresMeses;
  }

  public RespuestaADGVariablesDomicilio otorgantesCargaTresMesesNos(String otorgantesCargaTresMesesNos) {
    this.otorgantesCargaTresMesesNos = otorgantesCargaTresMesesNos;
    return this;
  }

   /**
   * Get otorgantesCargaTresMesesNos
   * @return otorgantesCargaTresMesesNos
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getOtorgantesCargaTresMesesNos() {
    return otorgantesCargaTresMesesNos;
  }

  public void setOtorgantesCargaTresMesesNos(String otorgantesCargaTresMesesNos) {
    this.otorgantesCargaTresMesesNos = otorgantesCargaTresMesesNos;
  }

  public RespuestaADGVariablesDomicilio servicioCarga(String servicioCarga) {
    this.servicioCarga = servicioCarga;
    return this;
  }

   /**
   * Get servicioCarga
   * @return servicioCarga
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getServicioCarga() {
    return servicioCarga;
  }

  public void setServicioCarga(String servicioCarga) {
    this.servicioCarga = servicioCarga;
  }

  public RespuestaADGVariablesDomicilio servicioCargaTresMeses(String servicioCargaTresMeses) {
    this.servicioCargaTresMeses = servicioCargaTresMeses;
    return this;
  }

   /**
   * Get servicioCargaTresMeses
   * @return servicioCargaTresMeses
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getServicioCargaTresMeses() {
    return servicioCargaTresMeses;
  }

  public void setServicioCargaTresMeses(String servicioCargaTresMeses) {
    this.servicioCargaTresMeses = servicioCargaTresMeses;
  }

  public RespuestaADGVariablesDomicilio servicioConsulta(String servicioConsulta) {
    this.servicioConsulta = servicioConsulta;
    return this;
  }

   /**
   * Get servicioConsulta
   * @return servicioConsulta
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getServicioConsulta() {
    return servicioConsulta;
  }

  public void setServicioConsulta(String servicioConsulta) {
    this.servicioConsulta = servicioConsulta;
  }

  public RespuestaADGVariablesDomicilio servicioConsultaTresMeses(String servicioConsultaTresMeses) {
    this.servicioConsultaTresMeses = servicioConsultaTresMeses;
    return this;
  }

   /**
   * Get servicioConsultaTresMeses
   * @return servicioConsultaTresMeses
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getServicioConsultaTresMeses() {
    return servicioConsultaTresMeses;
  }

  public void setServicioConsultaTresMeses(String servicioConsultaTresMeses) {
    this.servicioConsultaTresMeses = servicioConsultaTresMeses;
  }

  public RespuestaADGVariablesDomicilio numMiembros(String numMiembros) {
    this.numMiembros = numMiembros;
    return this;
  }

   /**
   * Get numMiembros
   * @return numMiembros
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getNumMiembros() {
    return numMiembros;
  }

  public void setNumMiembros(String numMiembros) {
    this.numMiembros = numMiembros;
  }

  public RespuestaADGVariablesDomicilio miembrosCredito(String miembrosCredito) {
    this.miembrosCredito = miembrosCredito;
    return this;
  }

   /**
   * Get miembrosCredito
   * @return miembrosCredito
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getMiembrosCredito() {
    return miembrosCredito;
  }

  public void setMiembrosCredito(String miembrosCredito) {
    this.miembrosCredito = miembrosCredito;
  }

  public RespuestaADGVariablesDomicilio miembrosCreditoS(String miembrosCreditoS) {
    this.miembrosCreditoS = miembrosCreditoS;
    return this;
  }

   /**
   * Get miembrosCreditoS
   * @return miembrosCreditoS
  **/
  @ApiModelProperty(example = "0", value = "")
  public String getMiembrosCreditoS() {
    return miembrosCreditoS;
  }

  public void setMiembrosCreditoS(String miembrosCreditoS) {
    this.miembrosCreditoS = miembrosCreditoS;
  }

  public RespuestaADGVariablesDomicilio miembrosCreditoNos(String miembrosCreditoNos) {
    this.miembrosCreditoNos = miembrosCreditoNos;
    return this;
  }

   /**
   * Get miembrosCreditoNos
   * @return miembrosCreditoNos
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getMiembrosCreditoNos() {
    return miembrosCreditoNos;
  }

  public void setMiembrosCreditoNos(String miembrosCreditoNos) {
    this.miembrosCreditoNos = miembrosCreditoNos;
  }

  public RespuestaADGVariablesDomicilio miembrosConsulta(String miembrosConsulta) {
    this.miembrosConsulta = miembrosConsulta;
    return this;
  }

   /**
   * Get miembrosConsulta
   * @return miembrosConsulta
  **/
  @ApiModelProperty(example = "2", value = "")
  public String getMiembrosConsulta() {
    return miembrosConsulta;
  }

  public void setMiembrosConsulta(String miembrosConsulta) {
    this.miembrosConsulta = miembrosConsulta;
  }

  public RespuestaADGVariablesDomicilio miembrosConsultaTresMeses(String miembrosConsultaTresMeses) {
    this.miembrosConsultaTresMeses = miembrosConsultaTresMeses;
    return this;
  }

   /**
   * Get miembrosConsultaTresMeses
   * @return miembrosConsultaTresMeses
  **/
  @ApiModelProperty(example = "1", value = "")
  public String getMiembrosConsultaTresMeses() {
    return miembrosConsultaTresMeses;
  }

  public void setMiembrosConsultaTresMeses(String miembrosConsultaTresMeses) {
    this.miembrosConsultaTresMeses = miembrosConsultaTresMeses;
  }

  public RespuestaADGVariablesDomicilio calif(String calif) {
    this.calif = calif;
    return this;
  }

   /**
   * Get calif
   * @return calif
  **/
  @ApiModelProperty(example = "16", value = "")
  public String getCalif() {
    return calif;
  }

  public void setCalif(String calif) {
    this.calif = calif;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespuestaADGVariablesDomicilio respuestaADGVariablesDomicilio = (RespuestaADGVariablesDomicilio) o;
    return Objects.equals(this.numeroCuenta, respuestaADGVariablesDomicilio.numeroCuenta) &&
        Objects.equals(this.folioDomicilio, respuestaADGVariablesDomicilio.folioDomicilio) &&
        Objects.equals(this.fechaUltimaConsulta, respuestaADGVariablesDomicilio.fechaUltimaConsulta) &&
        Objects.equals(this.numCreditos, respuestaADGVariablesDomicilio.numCreditos) &&
        Objects.equals(this.numCreditosTresMeses, respuestaADGVariablesDomicilio.numCreditosTresMeses) &&
        Objects.equals(this.numCreditosTresMesesNos, respuestaADGVariablesDomicilio.numCreditosTresMesesNos) &&
        Objects.equals(this.otorgantesConsulta, respuestaADGVariablesDomicilio.otorgantesConsulta) &&
        Objects.equals(this.otorgantesConsultaTresMeses, respuestaADGVariablesDomicilio.otorgantesConsultaTresMeses) &&
        Objects.equals(this.otorgantesCarga, respuestaADGVariablesDomicilio.otorgantesCarga) &&
        Objects.equals(this.otorgantesCargaTresMeses, respuestaADGVariablesDomicilio.otorgantesCargaTresMeses) &&
        Objects.equals(this.otorgantesCargaTresMesesNos, respuestaADGVariablesDomicilio.otorgantesCargaTresMesesNos) &&
        Objects.equals(this.servicioCarga, respuestaADGVariablesDomicilio.servicioCarga) &&
        Objects.equals(this.servicioCargaTresMeses, respuestaADGVariablesDomicilio.servicioCargaTresMeses) &&
        Objects.equals(this.servicioConsulta, respuestaADGVariablesDomicilio.servicioConsulta) &&
        Objects.equals(this.servicioConsultaTresMeses, respuestaADGVariablesDomicilio.servicioConsultaTresMeses) &&
        Objects.equals(this.numMiembros, respuestaADGVariablesDomicilio.numMiembros) &&
        Objects.equals(this.miembrosCredito, respuestaADGVariablesDomicilio.miembrosCredito) &&
        Objects.equals(this.miembrosCreditoS, respuestaADGVariablesDomicilio.miembrosCreditoS) &&
        Objects.equals(this.miembrosCreditoNos, respuestaADGVariablesDomicilio.miembrosCreditoNos) &&
        Objects.equals(this.miembrosConsulta, respuestaADGVariablesDomicilio.miembrosConsulta) &&
        Objects.equals(this.miembrosConsultaTresMeses, respuestaADGVariablesDomicilio.miembrosConsultaTresMeses) &&
        Objects.equals(this.calif, respuestaADGVariablesDomicilio.calif);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numeroCuenta, folioDomicilio, fechaUltimaConsulta, numCreditos, numCreditosTresMeses, numCreditosTresMesesNos, otorgantesConsulta, otorgantesConsultaTresMeses, otorgantesCarga, otorgantesCargaTresMeses, otorgantesCargaTresMesesNos, servicioCarga, servicioCargaTresMeses, servicioConsulta, servicioConsultaTresMeses, numMiembros, miembrosCredito, miembrosCreditoS, miembrosCreditoNos, miembrosConsulta, miembrosConsultaTresMeses, calif);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespuestaADGVariablesDomicilio {\n");
    
    sb.append("    numeroCuenta: ").append(toIndentedString(numeroCuenta)).append("\n");
    sb.append("    folioDomicilio: ").append(toIndentedString(folioDomicilio)).append("\n");
    sb.append("    fechaUltimaConsulta: ").append(toIndentedString(fechaUltimaConsulta)).append("\n");
    sb.append("    numCreditos: ").append(toIndentedString(numCreditos)).append("\n");
    sb.append("    numCreditosTresMeses: ").append(toIndentedString(numCreditosTresMeses)).append("\n");
    sb.append("    numCreditosTresMesesNos: ").append(toIndentedString(numCreditosTresMesesNos)).append("\n");
    sb.append("    otorgantesConsulta: ").append(toIndentedString(otorgantesConsulta)).append("\n");
    sb.append("    otorgantesConsultaTresMeses: ").append(toIndentedString(otorgantesConsultaTresMeses)).append("\n");
    sb.append("    otorgantesCarga: ").append(toIndentedString(otorgantesCarga)).append("\n");
    sb.append("    otorgantesCargaTresMeses: ").append(toIndentedString(otorgantesCargaTresMeses)).append("\n");
    sb.append("    otorgantesCargaTresMesesNos: ").append(toIndentedString(otorgantesCargaTresMesesNos)).append("\n");
    sb.append("    servicioCarga: ").append(toIndentedString(servicioCarga)).append("\n");
    sb.append("    servicioCargaTresMeses: ").append(toIndentedString(servicioCargaTresMeses)).append("\n");
    sb.append("    servicioConsulta: ").append(toIndentedString(servicioConsulta)).append("\n");
    sb.append("    servicioConsultaTresMeses: ").append(toIndentedString(servicioConsultaTresMeses)).append("\n");
    sb.append("    numMiembros: ").append(toIndentedString(numMiembros)).append("\n");
    sb.append("    miembrosCredito: ").append(toIndentedString(miembrosCredito)).append("\n");
    sb.append("    miembrosCreditoS: ").append(toIndentedString(miembrosCreditoS)).append("\n");
    sb.append("    miembrosCreditoNos: ").append(toIndentedString(miembrosCreditoNos)).append("\n");
    sb.append("    miembrosConsulta: ").append(toIndentedString(miembrosConsulta)).append("\n");
    sb.append("    miembrosConsultaTresMeses: ").append(toIndentedString(miembrosConsultaTresMeses)).append("\n");
    sb.append("    calif: ").append(toIndentedString(calif)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

